### ISSUE TITLE
a few errors after trying to run the app

### ISSUE THREAD

**Issue by scasia** [rbourgeat/llm-rp#16]
Hi, i'm getting a few errors while trying to get the app to work, installing openssl and pytorch didn't help, i followed the readme, what do I do? (Mac m2, Macos Sonoma beta 7)
`/Users/sasia/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/sasia/llm-rp/app/run.py", line 47, in <module>
    dpm = DPMSolverMultistepScheduler.from_pretrained(SD_MODEL, subfolder="scheduler")
  File "/Users/sasia/Library/Python/3.9/lib/python/site-packages/diffusers/utils/dummy_pt_objects.py", line 645, in from_pretrained
    requires_backends(cls, ["torch"])
  File "/Users/sasia/Library/Python/3.9/lib/python/site-packages/diffusers/utils/import_utils.py", line 540, in requires_backends
    raise ImportError("".join(failed))
ImportError: 
DPMSolverMultistepScheduler requires the PyTorch library but it was not found in your environment. Checkout the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.`

**Comment by rbourgeat** [comment]
Did you try another version of python, 3.8, 3.10 or 3.11?
